name: Deploy to dev
on: [push]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Clone repo
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            git clone https://github.com/Fonzeca/FastEmail.git
      - name: Actualizar repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            cd ./FastEmail
            git fetch --all && git reset --hard origin/main && git pull origin
      - name: Stop running container
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: false
          script: |
            cd ${{ secrets.PATH }}
            cd ./FastEmail
            docker compose stop
            docker compose rm -f
      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            cd ./FastEmail
            docker compose build
            docker compose up -d
      # - name: Connect to internal net
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: docker network connect carmind-net ${{ secrets.DOCKER_NAME}}